#!/usr/bin/env bash

python tools/iso646.py --cc 'JP'           --ir 14  -3 '#' -4 '$'  -A '@' -B '[' -C '¥'  -D ']' -E '^' -F '_' -a '`' -b '{' -c '|' -d '}' -e '‾' --cs 'iso-ir-14'  --cs 'ISO646-JP'                  --cs 'jp'                            --cs 'csISO14JISC6220ro'                               --cs 'JIS_C6220-1969-ro'     --cp 895             --mib 42  > mappings/public/iso646/646-jp.txt
python tools/iso646.py --cc 'JP OCR-B'     --ir 92  -3 '#' -4 '$'  -A '@' -B '‹' -C '¥'  -D '›' -E '^' -F '_' -a '`' -b '{' -c '|' -d '}' -e '‾' --cs 'iso-ir-92'  --cs 'ISO646-JP-OCR-B'            --cs 'jp-ocr-b'                      --cs 'csISO92JISC62991984b'                            --cs 'JIS_C6229-1984-b'                           --mib 68  > mappings/public/iso646/646-jp-ocr-​b.txt
python tools/iso646.py --cc 'KR'                    -3 '#' -4 '$'  -A '@' -B '[' -C '₩'  -D ']' -E '^' -F '_' -a '`' -b '{' -c '|' -d '}' -e '‾'                   --cs 'ISO646-KR'                                                       --cs 'csKSC5636'                                       --cs 'KSC5636'                                    --mib 102 > mappings/public/iso646/646-kr.txt
python tools/iso646.py --cc 'CN'           --ir 57  -3 '#' -4 '¥'  -A '@' -B '[' -C '\\' -D ']' -E '^' -F '_' -a '`' -b '{' -c '|' -d '}' -e '‾' --cs 'iso-ir-57'  --cs 'ISO646-CN'                  --cs 'cn'                            --cs 'csISO57GB1988'                                   --cs 'GB_1988-80'                                 --mib 56  > mappings/public/iso646/646-cn.txt
python tools/iso646.py --cc 'TW'                    -3 '#' -4 '$'  -A '@' -B '[' -C '\\' -D ']' -E '^' -F '_' -a '`' -b '{' -c '|' -d '}' -e '‾'                                                                                                                                                                                                             > mappings/public/iso646/646-tw.txt
python tools/iso646.py --cc 'IRV'          --ir 2   -3 '#' -4 '¤'  -A '@' -B '[' -C '\\' -D ']' -E '^' -F '_' -a '`' -b '{' -c '|' -d '}' -e '˜' --cs 'iso-ir-2'   --cs 'ISO_646.irv:1983'           --cs 'irv'                           --cs 'csISO2IntlRefVersion'                                                         --cp 1009 --cp 20105 --mib 30  > mappings/public/iso646/646-irv.txt
python tools/iso646.py --cc 'GB'           --ir 4   -3 '£' -4 '$'  -A '@' -B '[' -C '\\' -D ']' -E '^' -F '_' -a '`' -b '{' -c '|' -d '}' -e '‾' --cs 'iso-ir-4'   --cs 'ISO646-GB'                  --cs 'gb' --cs 'uk'                  --cs 'csISO4UnitedKingdom'                             --cs 'BS_4730'               --cp 1013            --mib 20  > mappings/public/iso646/646-gb.txt
python tools/iso646.py --cc 'DK'                    -3 '#' -4 '¤'  -A '@' -B 'Æ' -C 'Ø'  -D 'Å' -E 'Ü' -F '_' -a '`' -b 'æ' -c 'ø' -d 'å' -e 'ü'                   --cs 'ISO646-DK'                  --cs 'dk'                            --cs 'csISO646Danish'                                  --cs 'DS2089' --cs 'DS_2089' --cp 1017            --mib 99  > mappings/public/iso646/646-dk.txt
python tools/iso646.py --cc 'NO'           --ir 60  -3 '#' -4 '$'  -A '@' -B 'Æ' -C 'Ø'  -D 'Å' -E '^' -F '_' -a '`' -b 'æ' -c 'ø' -d 'å' -e '¯' --cs 'iso-ir-60'  --cs 'ISO646-NO'                  --cs 'no'                            --cs 'csISO60DanishNorwegian' --cs 'csISO60Norwegian1' --cs 'NS_4551-1'             --cp 1016            --mib 25  > mappings/public/iso646/646-no.txt
python tools/iso646.py --cc 'NO2'          --ir 61  -3 '§' -4 '$'  -A '@' -B 'Æ' -C 'Ø'  -D 'Å' -E '^' -F '_' -a '`' -b 'æ' -c 'ø' -d 'å' -e '|' --cs 'iso-ir-61'  --cs 'ISO646-NO2'                 --cs 'no2'                           --cs 'csISO61Norwegian2'                               --cs 'NS_4551-2'             --cp 20108           --mib 58  > mappings/public/iso646/646-no2.txt
python tools/iso646.py --cc 'FI' --cc 'SE' --ir 10  -3 '#' -4 '¤'  -A '@' -B 'Ä' -C 'Ö'  -D 'Å' -E '^' -F '_' -a '`' -b 'ä' -c 'ö' -d 'å' -e '¯' --cs 'iso-ir-10'  --cs 'ISO646-FI' --cs 'ISO646-SE' --cs 'fi' --cs 'se'                  --cs 'csISO10Swedish'                                  --cs 'SEN_850200_B'          --cp 1018            --mib 35  > mappings/public/iso646/646-se.txt
python tools/iso646.py --cc 'SE2'          --ir 11  -3 '#' -4 '¤'  -A 'É' -B 'Ä' -C 'Ö'  -D 'Å' -E 'Ü' -F '_' -a 'é' -b 'ä' -c 'ö' -d 'å' -e 'ü' --cs 'iso-ir-11'  --cs 'ISO646-SE2'                 --cs 'se2'                           --cs 'csISO11SwedishForNames'                          --cs 'SEN_850200_C'          --cp 20107           --mib 21  > mappings/public/iso646/646-se2.txt
python tools/iso646.py --cc 'DE'           --ir 21  -3 '#' -4 '$'  -A '§' -B 'Ä' -C 'Ö'  -D 'Ü' -E '^' -F '_' -a '`' -b 'ä' -c 'ö' -d 'ü' -e 'ß' --cs 'iso-ir-21'  --cs 'ISO646-DE'                  --cs 'de'                            --cs 'csISO21German'                                   --cs 'DIN_66003'             --cp 1011            --mib 24  > mappings/public/iso646/646-de.txt
python tools/iso646.py --cc 'HU'           --ir 86  -3 '#' -4 '¤'  -A 'Á' -B 'É' -C 'Ö'  -D 'Ü' -E '^' -F '_' -a 'á' -b 'é' -c 'ö' -d 'ü' -e '˝' --cs 'iso-ir-86'  --cs 'ISO646-HU'                  --cs 'hu'                            --cs 'csISO86Hungarian'                                --cs 'MSZ_7795.3'                                 --mib 62  > mappings/public/iso646/646-hu.txt
python tools/iso646.py --cc 'FR'           --ir 69  -3 '£' -4 '$'  -A 'à' -B '°' -C 'ç'  -D '§' -E '^' -F '_' -a 'µ' -b 'é' -c 'ù' -d 'è' -e '¨' --cs 'iso-ir-69'  --cs 'ISO646-FR'                  --cs 'fr'                            --cs 'csISO69French'                                   --cs 'NF_Z_62-010'           --cp 1010            --mib 26  > mappings/public/iso646/646-fr.txt
python tools/iso646.py --cc 'FR1'          --ir 25  -3 '£' -4 '$'  -A 'à' -B '°' -C 'ç'  -D '§' -E '^' -F '_' -a 'µ' -b 'é' -c 'ù' -d 'è' -e '¨' --cs 'iso-ir-25'  --cs 'ISO646-FR1'                                                      --cs 'csISO25French'                                   --cs 'NF_Z_62-010_(1973)'    --cp 1104            --mib 46  > mappings/public/iso646/646-fr1.txt
python tools/iso646.py --cc 'CA'           --ir 121 -3 '#' -4 '$'  -A 'à' -B 'â' -C 'ç'  -D 'ê' -E 'î' -F '_' -a 'ô' -b 'é' -c 'ù' -d 'è' -e 'û' --cs 'iso-ir-121' --cs 'ISO646-CA'                  --cs 'csa7-1' --cs 'csa71' --cs 'ca' --cs 'csISO121Canadian1'                               --cs 'CSA_Z243.4-1985-1'     --cp 1020            --mib 78  > mappings/public/iso646/646-ca.txt
python tools/iso646.py --cc 'CA2'          --ir 122 -3 '#' -4 '$'  -A 'à' -B 'â' -C 'ç'  -D 'ê' -E 'É' -F '_' -a 'ô' -b 'é' -c 'ù' -d 'è' -e 'û' --cs 'iso-ir-122' --cs 'ISO646-CA2'                 --cs 'csa7-2' --cs 'csa72'           --cs 'csISO122Canadian2'                               --cs 'CSA_Z243.4-1985-2'                          --mib 79  > mappings/public/iso646/646-ca2.txt
python tools/iso646.py --cc 'IE'           --ir 207 -3 '£' -4 '$'  -A 'Ó' -B 'É' -C 'Í'  -D 'Ú' -E 'Á' -F '_' -a 'ó' -b 'é' -c 'í' -d 'ú' -e 'á'                                                                                                                                                                                                             > mappings/public/iso646/646-ie.txt
python tools/iso646.py --cc 'IS'                    -3 '#' -4 '$'  -A 'Ð' -B 'Þ' -C '\\' -D 'Æ' -E 'Ö' -F '_' -a 'ð' -b 'þ' -c '|' -d 'æ' -e 'ö'                                                                                                                                                                                                             > mappings/public/iso646/646-is.txt
python tools/iso646.py --cc 'IT'           --ir 15  -3 '£' -4 '$'  -A '§' -B '°' -C 'ç'  -D 'é' -E '^' -F '_' -a 'ù' -b 'à' -c 'ò' -d 'è' -e 'ì' --cs 'iso-ir-15'  --cs 'ISO646-IT'                  --cs 'it'                            --cs 'csISO15Italian'                                                               --cp 1012            --mib 22  > mappings/public/iso646/646-it.txt
python tools/iso646.py --cc 'PT'           --ir 16  -3 '#' -4 '$'  -A '§' -B 'Ã' -C 'Ç'  -D 'Õ' -E '^' -F '_' -a '`' -b 'ã' -c 'ç' -d 'õ' -e '°' --cs 'iso-ir-16'  --cs 'ISO646-PT'                  --cs 'pt'                            --cs 'csISO16Portuguese'                                                                                 --mib 43  > mappings/public/iso646/646-pt.txt
python tools/iso646.py --cc 'PT2'          --ir 84  -3 '#' -4 '$'  -A '´' -B 'Ã' -C 'Ç'  -D 'Õ' -E '^' -F '_' -a '`' -b 'ã' -c 'ç' -d 'õ' -e '˜' --cs 'iso-ir-84'  --cs 'ISO646-PT2'                 --cs 'pt2'                           --cs 'csISO84Portuguese2'                                                           --cp 1015            --mib 60  > mappings/public/iso646/646-pt2.txt
python tools/iso646.py --cc 'ES'           --ir 17  -3 '#' -4 '$'  -A '§' -B '¡' -C 'Ñ'  -D '¿' -E '^' -F '_' -a '`' -b '°' -c 'ñ' -d 'ç' -e '˜' --cs 'iso-ir-17'  --cs 'ISO646-ES'                  --cs 'es'                            --cs 'csISO17Spanish'                                                               --cp 1023            --mib 23  > mappings/public/iso646/646-es.txt
python tools/iso646.py --cc 'ES2'          --ir 85  -3 '#' -4 '$'  -A '·' -B '¡' -C 'Ñ'  -D 'Ç' -E '¿' -F '_' -a '`' -b '´' -c 'ñ' -d 'ç' -e '¨' --cs 'iso-ir-85'  --cs 'ISO646-ES2'                 --cs 'es2'                           --cs 'csISO85Spanish2'                                                              --cp 1014            --mib 61  > mappings/public/iso646/646-es2.txt
python tools/iso646.py --cc 'CU'           --ir 151 -3 '#' -4 '¤'  -A '@' -B '¡' -C 'Ñ'  -D ']' -E '¿' -F '_' -a '`' -b '´' -c 'ñ' -d '[' -e '¨' --cs 'iso-ir-151' --cs 'ISO646-CU'                  --cs 'cuba'                          --cs 'csISO151Cuba'                                    --cs 'NC_NC00-10:81'                              --mib 92  > mappings/public/iso646/646-cu.txt
python tools/iso646.py --cc 'MT'                    -3 '#' -4 '$'  -A '@' -B 'ġ' -C 'ż'  -D 'ħ' -E '^' -F '_' -a 'ċ' -b 'Ġ' -c 'Ż' -d 'Ħ' -e 'Ċ'                                                                                                                                                                                                             > mappings/public/iso646/646-mt.txt
python tools/iso646.py --cc 'YU'           --ir 141 -3 '#' -4 '$'  -A 'Ž' -B 'Š' -C 'Đ'  -D 'Ć' -E 'Č' -F '_' -a 'ž' -b 'š' -c 'đ' -d 'ć' -e 'č' --cs 'iso-ir-141' --cs 'ISO646-YU'                  --cs 'js' --cs 'yu'                  --cs 'csISO141JUSIB1002'                               --cs 'JUS_I.B1.002'                               --mib 87  > mappings/public/iso646/646-yu.txt
python tools/iso646.py --cc 'NL'                    -3 '#' -4 '$'  -A '@' -B '[' -C '\\' -D ']' -E '^' -F '_' -a '`' -b '{' -c '|' -d '}' -e '¯'                                                                                                                                                                              --cp 1019                      > mappings/public/iso646/646-nl.txt
python tools/iso646.py --cc 'CH'                    -3 'ù' -4 '$'  -A 'à' -B 'é' -C 'ç'  -D 'ê' -E 'î' -F 'è' -a 'ô' -b 'ä' -c 'ö' -d 'ü' -e 'û'                                                                                                                                                                              --cp 1021                      > mappings/public/iso646/646-ch.txt
python tools/iso646.py --cc 'PL'                    -3 '#' -4 'zł' -A 'ę' -B 'ź' -C '\\' -D 'ń' -E 'ś' -F '_' -a 'ą' -b 'ó' -c 'ł' -d 'ż' -e 'ć'                                                                                                                                                                                                             > mappings/public/iso646/646-pl.txt
